### ISSUE TITLE
ldap.NO_SUCH_OBJECT AttributeError

### ISSUE THREAD

**Issue by GonzaloAlvarez** [gdub/python-simpleldap#9]
Hi,

   I'm trying to use simpleldap as installed from pip (version 0.8) and trying to issue a very simple connection:

``` python
self.conn = simpleldap.Connection(hostname=self.hostname, dn=self.dn, password=self.password, encryption=self.encryption, require_cert=False)
```

but I'm getting the following error:

```
Traceback (most recent call last):
  File "ldap.py", line 3, in <module>
    import logging, yaml, simpleldap
  File "/usr/local/lib/python2.7/dist-packages/simpleldap/__init__.py", line 93, in <module>
    class Connection(object):
  File "/usr/local/lib/python2.7/dist-packages/simpleldap/__init__.py", line 105, in Connection
    ldap.NO_SUCH_OBJECT,  # e.g. dn matches no objects.
AttributeError: 'module' object has no attribute 'NO_SUCH_OBJECT'
```

Am I missing something?

Thanks!

**Comment by gdub** [comment]
It appears that your source file is named ldap.py, and if you are running from the directory that contains your ldap.py module it would end up masking the external ldap library that simpleldap uses.  

If you rename your file to something other than ldap.py, does that fix the error?

Alternatively, you could ensure that you don't run from the same directory containing your ldap.py module, as your current working directory gets added to your PYTHONPATH and thus any modules named the same as an external library will import the module from the current directory instead of the external library that was intended.

**Comment by GonzaloAlvarez** [comment]
Indeed, that was the reason!! Thanks a lot!
